# Generated by Django 4.2 on 2025-09-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_no', models.CharField(blank=True, max_length=155, null=True)),
                ('order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('address_id', models.IntegerField(blank=True, null=True)),
                ('pay_status', models.CharField(blank=True, max_length=155, null=True)),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('ali_trade_no', models.CharField(blank=True, max_length=255, null=True)),
                ('is_delete', models.PositiveIntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(blank=True, max_length=255, null=True)),
                ('sku_id', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_goods',
                'managed': False,
            },
        ),
    ]
